/*
dbcc dropcleanbuffers;
dbcc freeproccache;
*/

declare @PENNIES int = 100000;

select
	FINANCIALTRANSACTION.ID,
	FINANCIALTRANSACTION.CONSTITUENTID,
	FINANCIALTRANSACTION.TRANSACTIONAMOUNT
from
	dbo.FINANCIALTRANSACTION
where
	TRANSACTIONAMOUNT * 100 = @PENNIES

/*
dbcc dropcleanbuffers;
dbcc freeproccache;
*/

select
	FINANCIALTRANSACTION.ID,
	FINANCIALTRANSACTION.CONSTITUENTID,
	FINANCIALTRANSACTION.TRANSACTIONAMOUNT
from
	dbo.FINANCIALTRANSACTION
where
	TRANSACTIONAMOUNT = @PENNIES / 100
