/*
drop procedure dbo.USP_TEST_RESTRUCTURINGQUERIES_XQUERY
*/

create procedure dbo.USP_TEST_RESTRUCTURINGQUERIES_XQUERY(
	@DESIGNATIONSXML as xml
)
as
	set nocount on;
		
	select 
		FINANCIALTRANSACTION.ID
	from 
		dbo.FINANCIALTRANSACTION
		inner join dbo.FINANCIALTRANSACTIONLINEITEM on FINANCIALTRANSACTIONLINEITEM.FINANCIALTRANSACTIONID = FINANCIALTRANSACTION.ID
		inner join dbo.REVENUESPLIT_EXT on REVENUESPLIT_EXT.ID = FINANCIALTRANSACTIONLINEITEM.ID
		inner join (select T.c.value('(ID)[1]','uniqueidentifier') ID from @DESIGNATIONSXML.nodes('/DESIGNATIONS/ITEM') T(c)) DESIGNATIONS on DESIGNATIONS.ID = REVENUESPLIT_EXT.DESIGNATIONID
	where
		FINANCIALTRANSACTION.DATE >= '1/1/2013' and FINANCIALTRANSACTION.DATE < '1/1/2014'

go

/*
drop procedure dbo.USP_TEST_RESTRUCTURINGQUERIES_TABLEVARIABLE
*/

create procedure dbo.USP_TEST_RESTRUCTURINGQUERIES_TABLEVARIABLE(
	@DESIGNATIONSXML as xml
)
as
	set nocount on;

	declare @DESIGNATIONS table (
		ID uniqueidentifier
	)

	insert into @DESIGNATIONS
	select T.c.value('(ID)[1]','uniqueidentifier')
	from @DESIGNATIONSXML.nodes('/DESIGNATIONS/ITEM') T(c);

	select 
		FINANCIALTRANSACTION.ID
	from 
		dbo.FINANCIALTRANSACTION
		inner join dbo.FINANCIALTRANSACTIONLINEITEM on FINANCIALTRANSACTIONLINEITEM.FINANCIALTRANSACTIONID = FINANCIALTRANSACTION.ID
		inner join dbo.REVENUESPLIT_EXT on REVENUESPLIT_EXT.ID = FINANCIALTRANSACTIONLINEITEM.ID
		inner join @DESIGNATIONS DESIGNATIONS on DESIGNATIONS.ID = REVENUESPLIT_EXT.DESIGNATIONID
	where
		FINANCIALTRANSACTION.DATE >= '1/1/2013' and FINANCIALTRANSACTION.DATE < '1/1/2014'

go

/*
drop procedure dbo.USP_TEST_RESTRUCTURINGQUERIES_TEMPTABLE
*/

create procedure dbo.USP_TEST_RESTRUCTURINGQUERIES_TEMPTABLE(
	@DESIGNATIONSXML as xml
)
as
	set nocount on;

	create table #TMP_TEST_DESIGNATIONS  (
		ID uniqueidentifier
	)

	insert into #TMP_TEST_DESIGNATIONS
	select T.c.value('(ID)[1]','uniqueidentifier')
	from @DESIGNATIONSXML.nodes('/DESIGNATIONS/ITEM') T(c);

	select 
		FINANCIALTRANSACTION.ID
	from 
		dbo.FINANCIALTRANSACTION
		inner join dbo.FINANCIALTRANSACTIONLINEITEM on FINANCIALTRANSACTIONLINEITEM.FINANCIALTRANSACTIONID = FINANCIALTRANSACTION.ID
		inner join dbo.REVENUESPLIT_EXT on REVENUESPLIT_EXT.ID = FINANCIALTRANSACTIONLINEITEM.ID
		inner join #TMP_TEST_DESIGNATIONS DESIGNATIONS on DESIGNATIONS.ID = REVENUESPLIT_EXT.DESIGNATIONID
	where
		FINANCIALTRANSACTION.DATE >= '1/1/2013' and FINANCIALTRANSACTION.DATE < '1/1/2014'
	
	drop table #TMP_TEST_DESIGNATIONS;

go
