
declare @ATTRIBUTENAME nvarchar(200) = 'DEMO3DATE'
declare @ATTRIBUTETABLENAME nvarchar(200)

select @ATTRIBUTETABLENAME = TC.TABLENAME
from ATTRIBUTECATEGORY AC inner join TABLECATALOG TC on AC.TABLECATALOGID = TC.ID
where AC.NAME = @ATTRIBUTENAME

if exists (select top 1 1 from sys.all_objects where name = 'USR_SYN_CONSTITUENT_DEMO3DATE' and type_desc = 'SYNONYM')
    drop synonym USR_SYN_CONSTITUENT_DEMO3DATE

exec('CREATE SYNONYM USR_SYN_CONSTITUENT_DEMO3DATE FOR ' + @ATTRIBUTETABLENAME)










